# Generated by Django 5.2.7 on 2025-10-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_attendance_options_remove_student_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='students', to='myapp.class'),
        ),
    ]
